---
- name: playbook for simple x GB partition
  hosts: linux1
  become: true
  
  tasks:
    - name: create partition
      parted:
        device: /dev/sdb
        number: 1
        flags:  [lvm]
        state: present
        part_end: 4GiB

    - name: create volume group
      lvg:
        vg: sample-vg
        pvs: /dev/sdb1
        pesize: 32
        #force: yes
    
    - name: install lvm2 dependency
      package:
        name: lvm2
        state: present

    - name: create logical volume
      lvol:
        vg: sample-vg
        lv: sample-lv
        size: "512m"
        #force: yes            

    - name: create directory
      file:
        path: /data1
        state: directory
        mode: '0755'

    - name: format ext4
      filesystem:
        fstype: ext4
        dev: /dev/sample-vg/sample-lv

    - name: mount lv on /data1
      mount:
        path: /data1
        src: /dev/sample-vg/sample-lv
        fstype: ext4
        state: mounted


